name: CI

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [11, 17]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: Notify on success
        if: success()
        run: echo "Tests passed!"

      - name: Notify on failure
        if: failure()
        run: echo "Tests failed!"
